
stages:
  - build
  - deploy

image: docker:20.10.5
services:
  - docker:20.10.5-dind

# Определяем переменные для удобства
variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/hello:gitlab-$CI_COMMIT_SHORT_SHA"

build-job:
  stage: build
  script:
    # Логинимся в GitLab Container Registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    
    # Собираем Docker image
    - docker build -t $DOCKER_IMAGE .
    
    # Пушим image в GitLab Container Registry
    - docker push $DOCKER_IMAGE
    
    - echo "Docker image $DOCKER_IMAGE successfully built and pushed."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

